### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by chrunchyjesus**
Some of the dependencies are so old my project which depends on this crate pulls multiple versions of the same crate like `syn`.

### CODE REVIEW

**Comment by DCjanus** [comment]
Blocked by https://github.com/chrunchyjesus/atom/pull/1

**Comment by chrunchyjesus** [comment]
> Blocked by [chrunchyjesus#1](https://github.com/chrunchyjesus/atom/pull/1)

Fixed.

**Comment by DCjanus** [comment]
LGTM, merged

**Comment by DCjanus** [comment]
I'm going to release a new version in three days, if there is any issue, please contact me.

**Pull request merged**
