### PR TITLE
Add support for stylesheet

### PR DESCRIPTION
**Pull request by jacobkiers**
I'm working on a project to convert newsletters to an atom feed. I'd like to add a style sheet as well. This PR makes sure I can set a style sheet URL on the feed, and write it when generating the XML.

### CODE REVIEW

**Comment by jacobkiers** [comment]
It replaces this ugly thing:

```rs
let feed_str = feed.to_string().as_str()
    .replace(">\n<feed", ">\n<?xml-stylesheet href=\"feed.xsl\" type=\"text/xsl\"?>\n<feed");
```

**Comment by andy128k** [comment]
i am slightly concerned about this change having that atom spec says nothing about style sheets.

**Comment by jacobkiers** [comment]
I think that is because the atom spec deals with anything that is within the `<feed>` tag, as you can see from [section 2 of the spec](https://www.rfc-editor.org/rfc/rfc4287#section-2).

The style sheet comes _before_ that and is a standard XML Style Sheet (XSL)., as you can see in this example:

```xml
<?xml version="1.0"?>
<?xml-stylesheet href="feed.xsl" type="text/xsl"?>
<feed xmlns="http://www.w3.org/2005/Atom">
```

**Comment by jacobkiers** [comment]
Also, if you put this in the [feed validator](https://validator.w3.org/feed/#validate_by_input), it will tell you it's a valid feed:

```xml
<?xml version="1.0"?>
<?xml-stylesheet href="feed.xsl" type="text/xsl"?>
<feed xmlns="http://www.w3.org/2005/Atom">
<title>Test Feed</title>
<id>https://example.org/feed.atom</id><updated>2022-01-01T00:00:00+00:00</updated>
<link href="https://example.org/feed.atom" rel="self"/></feed>
```

**Comment by jacobkiers** [comment]
@andy128k Did you get around to look into this yet?

**Comment by andy128k** [comment]
@jacobkiers Tough situation :) Frankly, I don't like the idea to add anything outside from Atom spec.
On the other hand I realize that people need to do strange things with their feeds.

I think, I have a better idea to address your specific issue. Have a look at #70. With such configuration, you could have smth like this

```rust
let out = File::create("out.xml").unwrap();
writeln!(out, "<?xml version="1.0"?>");
writeln!(out, "<?xml-stylesheet href="feed.xsl" type="text/xsl"?>");
let config = WriteConfig {
    write_document_declaration: false,
    ..Default::default()
};
feed.write(out, config).unwrap();
```

**Comment by jacobkiers** [comment]
@andy128k I tried it, that works fine, and is perfectly acceptable to me as well.

**Pull request closed without merging**
